### ISSUE TITLE
Add Code of Conduct to website

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#10]
### Summary

Establish Code of conduct for the community and it's management

### Detail

This Code of Conduct can also live on the website, but should be available here as well!

**Comment by manics** [comment]
There's a central CoC in https://github.com/uk-tre/.github
which is automatically attached to every repo in this org:
![image](https://github.com/uk-tre/community-management/assets/1644105/87b8a4d0-166c-4d2e-b107-678738ca9372)

**Comment by hardakerm** [comment]
That looks pretty comprehensive and covers the essential elements imo - we could expand on expectations for community benefit, transparency, open ways of working etc. if that felt like a good fit

**Comment by MichelleAmugi** [comment]
I am happy to begin drafting something.

**Comment by JimMadge** [comment]
I would advocate for not reinventing the wheel when it comes to a CoC.
Is there any reason why contributor covenant wouldn't work?

**Comment by JimMadge** [comment]
I'm happy with the existing CoC.

**Comment by harisood** [comment]
Cool agreed this is good! have amended issue to j say 'add to website'
