### ISSUE TITLE
June event catch all issue

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#101]
### Detail

Sorry if duplicate did not see.

Issue for everything related to the June event on 5th June

### Actions

- [x] Registration page
- [x] Collect ideas for Breaout rooms
- [x] Agree keynote topic
- [x] Send reminder
- [x] Set up zoom room and logistics
- [x] Create agenda
- [x] hackmd for discussions

**Comment by Davsarper** [comment]
Meeting notes:
- Track/talk/webinar on different TREs and how/why the came to be they way they are, they key characteristics

**Comment by manics** [comment]
Keynote ideas:
- SERP/SAIL
- Genomics England
- ELIXIR

@hardakerm will ask Tim
Event: Wednesday 5th June 2024 13:30 - 17:00. Keynote talk: 30 mins + 15 min questions. Ideally starting at 13:45 but can be flexible.
https://www.uktre.org/en/latest/events/wg_workshops/2024-06-05-june-meeting/index.html

**Comment by manics** [comment]
@manics: setup hackmds and provisional schedule
@Davsarper: will setup zoom

**Comment by Davsarper** [comment]
- Do we need a keynote for June or spend more time on Community updates?
 - It is a nice, anchoring part of the event
 - We could use more time to work
 - If no keynote, time still needs to be together (no more breakout rooms)
- Crick could do a keynote on how it does TREs and its approach
- Decide today, go via slack for an executive yet not clsoed decision
 - [ ] Propose today via slack what they want
 - [ ] ask to come up with a keynote
 - [ ] if not choose Community update

IF only community updates: what are the timings? We would have total an 60' and so can do an update, working groups share for say 5' and then general discussion

**Comment by Davsarper** [comment]
Current breakout rooms suggestions are not that many so probably yes to all AND a push to the community for more

**Comment by Davsarper** [comment]
- [ ] Say yes to proponents
- [ ] Share templates to populate
- [ ] create first version of the agenda
- [ ] Add details from templates to agenda and web

**Comment by Davsarper** [comment]
Update on the above:
DHSC want to run a session that given the level of detail can perfectly be a keynote, so reach out today and propose. If not go with Community updates and WG for longer.

**Comment by Davsarper** [comment]
DHSC no longer can give the keynote (or breakout) due to the upcoming election.

We will use the time to an extended community update

**Comment by Davsarper** [comment]
Proposal from Crick to do an introductory presentation on their TRE approach, agreement for this in the meeting and on slack to go with this as there is interest.

Idea is 30 min instead of 45 so there is proper time for WGs to also make their updates.

@Davsarper can lead a breakout room if there is interest to explore in more detail what we have done over this period and the new governance doc/processes

**Comment by Davsarper** [comment]
Actions:
- [ ] Remind chairs about a 5ish minutes updates on their Working Group
- [ ] Update agenda 
  - [ ] On web
  - [ ] On event
- [ ] Send the same to Understanding patient data

**Comment by manics** [comment]
- [ ] Todo: add online/in-person option to registration form
