### ISSUE TITLE
Working group follow up - catch all

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#102]
### Detail

- [x] Collect all charters
- [x] Review charters by this group and check that
  - [x] They align with our principles
  - [x] Work is not duplicated
- [x] Share charter for community review and objections
- [ ] Add events and meetings to public calendar
- [x]  Communicate with community
- [ ] Clarify process for everyone and make it evident 

### Actions

- [x] Collect all charters
- [x] Review charters by this group and check that
  - [x] They align with our principles
  - [x] Work is not duplicated
- [x] Share charter for community review and objections
- [ ] Add events and meetings to public calendar
- [ ]  Communicate with community
- [ ] Clarify process for everyone and make it evident

**Comment by Davsarper** [comment]
COntact WG lead and ask to:
- Add all current feedback to charters
- When happy share with CMWG
  - Store where WG prefers: drive, repo or anything else but publicly available
- CMWG review
- If happy share link with community for review
- After a period of time publish as official

**Comment by Davsarper** [comment]
Meeting notes:
- Follow up with the community from the event, summary and outputs, how to contact and become involved. 
- Aim for end of this week.
- There is a lot happening so the CMWG has a job to summarize it all and help make sense of it.
 - With no "dedicated resource" now, we have to hit the right balance of providing structure/processes and be capable of delivering
 - Make clear to WGs what they are expected to do
 - Coordinate charters and official comms from CMWG, make it clear. All work by WGs

**Comment by Davsarper** [comment]
We have to update the website, take down old WGs and update with new

**Comment by balintstewart77** [comment]
> Meeting notes:
> 
> * Follow up with the community from the event, summary and outputs, how to contact and become involved.
> * Aim for end of this week.
> * There is a lot happening so the CMWG has a job to summarize it all and help make sense of it.
> * With no "dedicated resource" now, we have to hit the right balance of providing structure/processes and be capable of delivering
> * Make clear to WGs what they are expected to do
> * Coordinate charters and official comms from CMWG, make it clear. All work by WGs
> * How-tos
> 
> Actions for follow up:
> 
> * [ ]  Ask all info from WG co-chairs @Davsarper
>   
>   * [ ]  Charter
>   * [ ]  How they are meeting, and when. Suggest that they establish them
>   * [ ]  How they are working
>   * [ ]  How to be contacted
> * [ ]  Where possible update public calendar with meetings
> * [ ]  Send email with all charters, contacts and calendar
>   
>   * [ ]  Add links to governance docs and clarify process/steps that will happen
> * [ ]  Update read the docs webpage in the interim (@manics unless you think we will migrate immediately) or update directly on the hugo website
>   
>   * [ ]  @balintstewart77 to update read-the-docs
> * [ ]  Slack channels for those who want it
> * [ ]  Suggest jiscmail lists , pointing to how to do it

@Davsarper Thanks for this David: suggest when approaching co-chairs this week we ask for the following: 
- WG title
- One short para on the objectives of the WG
- Who the co-chairs are, and their emails
- How to get involved in the WG (e.g. join mailing list)
- Link to draft charter (if available)

We can then simply copy paste this into an email in the follow-up (it's okay if they don't yet have all this info), and also into the Readthedocs/Hugo website. Wdyt?

**Comment by Davsarper** [comment]
Totally agree @balintstewart77 , I am preparing an email just this moment and will share with you then send

**Comment by manics** [comment]
Charters are available for comment (Dropbox, Google docs, depending on WG). This is acceptable for now

**Comment by manics** [comment]
@Davsarper to send out reminder email for everyone to review charters tomorrow

**Comment by Davsarper** [comment]
All working groups approved!
- [ ] Make an official communication about it - @Davsarper

**Comment by Davsarper** [comment]
## 25 June meeting

- Raised concerned: is there not enough engagement with WGs? No objections but also no feedback, no attendees to some WG meetings.

- A place to keep a record of ideas and interests, thinking of those WG that we know we want to do but no one can. Can we save the work done so far, the ideas etc. for a future moment of time?
 - Should we keep a record/contact info of those expressing interest

**Comment by manics** [comment]
To be incorporated into UK TRE meeting presentation
