### ISSUE TITLE
Apply for UKRI Digital Research Technical Professional Skills NetworkPlus grant

### ISSUE THREAD

**Issue by manics** [uk-tre/community-management#105]
### Detail

Deadline: 27 June 2024 4:00pm UK time
Amount: £1m-£2m
Length: 4 years

https://www.ukri.org/opportunity/ukri-digital-research-technical-professional-skills-networkplus/

> Apply for funding for a Digital Research Technical Professional (RTP) Skills NetworkPlus, which brings together disciplines, sectors, and domains to address cross-cutting challenges related to digital RTP skills and careers.
>
> You will provide leadership, coordinate collaborations, seed better ways of working, and catalyse learning, capability, and capacity for digital RTPs.

I think advancing the UK TRE fits within the scope. We're cover multiple disciplines, we have a diverse community centred around secure research which provides benefits to all members, we're aware of several areas lacking in skills, and we're aware of how hard it is to run a community with no resources.

As well as asking for funding to sustain the community we could aim to setup a training program for researchers working in TREs, which is something we know we're lacking in the UK.

We could also use this to partially fund working group chairs, as well as providing resources for meetings.

Could we fund a part-time public representative for UK TRE to provide advice/assistance across all our activities?

### Actions

- [ ] Decide whether to apply for the grant
- [ ] Find institutions and people interested in collaborating
- [ ] Write the grant!

**Comment by Davsarper** [comment]
Did a first reading, I agree we can properly justify the UK TRE Community as fitting within the scope. While we are a community centred on TREs these require a wide set of professionals and disciplinas, and are domain agnostic (acknowledge Health weiight in the space).

Some of what we already do is directy fundable, and we could ask for support to conitnue doing it and do it better/more: events, discussions spaces

The resource hub is an ongoing thing this grant could foster and make it properly happen

We currently lack initiatives more focused on Skills as @manics indicates, agreed it could be something to propose.

Work on career path and workforce retention could be valuable, some members have been mentioning at meetings. How the TRE space has no formal path recognised which makes retention more difficult. We coudl define roles and make recommendations

**Comment by Davsarper** [comment]
Partners? Turing, HIC, PEDRI (? what angle), SDAP

It is a lot of money: what would we be giving back? The community itself (run and solidify, run events, networking), fund people to do the leg work, maybe working groups leads to have aside time, time for people who want to participate but can't. One option is also to combine, either to get to the 1M or to go for the 2M (say if we joined with PEDRI and they wanted to do lots of workshops).

We need a 1/2 page write up: let's start a shared document, Pete will have a stab today 

Letters of support: everyone but minimum the parent organisations of this group

**Comment by Davsarper** [comment]
- Turing cannot be lead and submit currently
- Kings could maybe submit
- Crick is also an option
- Any other submissions in the community we can join forces with?

Shout out about the skills grant

**Comment by Davsarper** [comment]
During the 5th June event #101 we want at a minimum letters of support from members.

We need to include a high level proposal and ask folk to be ready to put together letters of support.

Maybe as  as well a shout out for ideas on how to make the submission happen, any other orgs submitting that want to include us or be leads

**Comment by Davsarper** [comment]
- [ ] set up a separate meeting/series to work on this - @Davsarper 
- [ ] 1st session CMWG - work, plan, clarify the asks to the community
- [ ] Share and invite the community for feedback and contributions
- [ ] Go back and write it
