### ISSUE TITLE
June event: UK TRE & NHSE SDE Network breakout room

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#108]
### Detail

Data Access team in DHSC/NHS joint Digital POlicy & strategy Unit members registered for June event and have proposed a breakout room.

They have to leave at 4 so they request to be added to the first round of breakouts.

Relates to #101 

### Actions

- [ ] Add more information from registration form
- [ ] Include in the agenda
- [ ] Send templates for breakout leads and instructions

**Comment by manics** [comment]
On hold, due to pending election prohibiting discussion of Government policy
