### ISSUE TITLE
PEDRI for a breakout or keynote at an event (june?)

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#110]
### Detail

PEDRI is doing a lot of work on creating and signposting resources on PPIE, an area of clear interest to this community but which has not taken off/has lots of members.

A talk during an event could help coalesce that, it might even be a good idea to make it a keynote at some point.

### Actions

- [ ] Discuss the idea
- [ ] Discuss PPIE in the UK TRe Community
- [ ] Develop an specific ask for PEDRI
- [ ] Add to this list
- [ ]

**Comment by manics** [comment]
See https://github.com/uk-tre/community-management/issues/125
