### ISSUE TITLE
Write up June 2024 event notes and other post-event tasks

### ISSUE THREAD

**Issue by manics** [uk-tre/community-management#120]
- [x] Cleanup raw hackmd notes and add to website
- [ ] Write summary of event and add to website
- [x] Upload recording to YouTube
- [ ] Review event feedback

**Comment by manics** [comment]
@Davsarper was very efficient and uploaded the YouTube recording ages ago! https://www.youtube.com/watch?v=1FqVEP0OVlY

**Comment by balintstewart77** [comment]
> @Davsarper was very efficient and uploaded the YouTube recording ages ago! https://www.youtube.com/watch?v=1FqVEP0OVlY

Wowzer, kudos David!

**Comment by balintstewart77** [comment]
> * [ ]  Cleanup raw hackmd notes and add to website
> * [ ]  Write summary of event and add to website
> * [x]  Upload recording to YouTube

Can we also review any responses to the feedback form at some point? Probably doesn't need writing up but would be nice cover it at CMWG meeting sometime soon

**Comment by Davsarper** [comment]
No responses... we may need to ensure we have it ready on the day next time. And I think shorten it

**Comment by manics** [comment]
Decided we don't need a summary, it's good enough as it it!

**Comment by Davsarper** [comment]
no feedback still, closing issue
