### ISSUE TITLE
Publish notes from UKTRE24

### ISSUE THREAD

**Issue by manics** [uk-tre/community-management#124]
### Detail

- Write-up summary of day
- Clean-up hack.md notes:
  - Remove most names
  - Fix formatting so it displays well in Markdown
  - If there are any external images either add them to this repo, or if hosted externally ensure they won't be deleted by someone
  - Fix any typos and grammatical errors

~strikeout~ means no notes were taken

## Overall summary
- [ ] Write-up overall high-level summary of day (themes, general feelings) (Balint)

## Keynotes
Clean up notes

- [x] [Federation: Accelerating digital science Panel](https://hackmd.io/-y3dbsS2T-GUxaQHcEuNAQ?edit) (pete)

## Breakouts: Accelerating digital science
Clean up notes

- [ ] Summarise all breakouts (Pete, David)

### Online:
  - [x] [Room 1](https://hackmd.io/B83IzL0MS5GpoOIkjWZq7A?edit)
  - [x] [Room 2](https://hackmd.io/7Hh0bocXRPGofUDHpAMUxQ?edit)
  - [ ] ~[Room 3](https://hackmd.io/_1M8Cg_MRsuPko0pb7P16Q?edit)~
  - [x] [Room 4](https://hackmd.io/mgJ2OaeoQWCsGCJ8r6oWXw?edit)
  - [ ] ~[Room 5](https://hackmd.io/mkgM2AhsTpCf57Rk8Kv6fw?edit)~
  - [x] [Room 6](https://hackmd.io/_pjBXzUdSvW0H-hS3BeIWA?edit)
  - [x] [Room 7](https://hackmd.io/1WeWA7GbTSKfgRFXtrS3cQ?edit)
  - [ ] ~[Room 8](https://hackmd.io/TOiSJ11sQ5GDIb_KktaHog?edit)~
  - [ ] ~[Room 9](https://hackmd.io/p4X0YporT6-UTe5Tn4OHSw?edit)~
  - [x] [Room 10](https://hackmd.io/-pmIH7lqTZK2EDmkl1p_5A?edit)

### In-person G.06:
  - [ ] [Room 11](https://hackmd.io/go4v7tCgTyO17Nb_-vgfvg?edit)
  - [ ] ~[Room 12](https://hackmd.io/wDCjCrUyTIeu3X7SKrJrig?edit)~

### In-person F1.17:
  - [ ] [Room 13](https://hackmd.io/Dmfpn1VDQNa8p-6nW5Wf_w?edit)
  - [ ] [Room 14](https://hackmd.io/7Gg5PtPwTW-sUxlXL9TF3g?edit)
  - [ ] [Room 15](https://hackmd.io/CKEsX2m0Q1ahATCl-xFeoQ?edit)
  - [ ] [Room 16](https://hackmd.io/bYhcGy8gRf-piqoONe-uKw)
  - [ ] [Room 17](https://hackmd.io/tSzWDQSaTey3kzZruO02ag)
  - [ ] ~[Room 18](https://hackmd.io/TRFWkXwTQjWKFiGtdIJJxA)~
  - [ ] ~[Room 19](https://hackmd.io/ZEMif73GSPeniNyqZpl8vg)~
  - [ ] ~[Room 20](https://hackmd.io/7thic3-GSCyjYdjDJaorzA)~

## Afternoon sessions: Collaborative notes
Clean up notes

### Working Groups:
  - [ ] ~[Citizen Agency](https://hackmd.io/XHjqO1PKQkmSa3TaLJPQbg?edit)~
  - [x] [Extending Control](https://hackmd.io/blNnDouARzmv5aVRPn3wwg?edit) (pete)
  - [x] [CyberSecurity Risk](https://hackmd.io/4Yy7p11hS8OSJRiUmnkkLg?edit) (Simon)
  - [x] [Funding & Sustainability](https://hackmd.io/_b9hcE3UQJ-2QSBi7V7ucw?edit) (Simon)
  - [x] [SATRE](https://hackmd.io/983qhOPoR2W6V6ryyZ9AxQ?edit) (Simon)
  - [ ] ~[TRE Glossary](https://hackmd.io/mJ7sXSVxS0eOG0QmAlbe5g?edit)~
  - [ ] ~[SDE/TRE Definitions](https://hackmd.io/fc8V-6jwSUCAm31zcJtcWw?edit)~

### Community topics:
  - [ ] ~[Breakout 1](https://hackmd.io/n9Bfz_6mQFqbhp7bcOmHVg?edit)~
  - [ ] ~[Breakout 2](https://hackmd.io/4lk_VYn1RGiv-RVPW6dG9Q?edit)~
  - [ ] ~[Breakout 3](https://hackmd.io/trHzTe7xTrK2mp1pkqwwBg?edit)~
  - [ ] ~[Breakout 4](https://hackmd.io/KMwqykRkRMShaxR8680epg?edit)~
  - [ ] ~[Breakout 5](https://hackmd.io/aOn96_wiT3WMqfrQs-L_Jg?edit)~
  - [ ] ~[Breakout 6](https://hackmd.io/vCzjxkiUQMe0pl8rUtojKQ?edit)~
  - [ ] ~[Breakout 7](https://hackmd.io/vSieqvXYSUCZOKtKq5QGug?edit)~

### Lightning talks and Dare UK Phase 2
Clean up notes

- [ ] ~[Lightning talks](https://hackmd.io/cvK_Y6IWQICflpkQl54kEA?edit)~

- [ ] ~[Dare UK Phase 2](https://hackmd.io/t9aKMslAQ7-FAuqxUr0m2A?edit)~

### Who can help

Everyone!

**Comment by manics** [comment]
SImon: Upload to Zenodo (private draft, pending approval from everyone to publish)

**Comment by crickpetebarnsley** [comment]
@manics  Simon   I have edited the HAackMD again and copy that below

My summary for the "Extending Control" working group breakout.  I have reviewed the HCKMD and think there are no real worries about formatting etc.

But we could add a comment to say that the breakout was well attended with >10 people (James says it was very well attended making it hard to manage in the room and also had people online.

I assume we will remove all the blank X in the attendees etc.

## Attendees
- Chair: James Fleming (standing in for Pete Barnsley)
- Note-taker: Diane Brown
- Nicola Armstrong, HSC R&D Division, HSCNI
- Liz Merrifield, Cardiff University
- This session was very well attended but names not recorded:

## Prompts
- see Notes for Problem questions

## Notes
Problems? 
1. How to minimise time to research?
2. How to combine datasets easily?  <-- physically? logically/virtually?
3. Citizens agency

Typically local information governance around one dataset at a time. However, how can we bring together many datasets while maintaining some information governance boundary?

Data federation in current practice / examples
- OMOP model for health datasets
- Should there be a playbook to work too? OMOP is a 'step' in a playbook for standardising.
- Open Safely (but limitation in data - COVID, Primary GP data) 
- UK LLC (longitudinal studies) single governance access route across data from the various lonitudinal studies
- Scottish Regional Safe Haven Network Federated Governance project
- FEMS
- Synthetic Data Project across Scottish Safe Havens
- Scotland Caldicott Guardian sharing / accepting liability 

What's common and what's distinct across the existing ferderated projects around governance?

What changes do we want to see? Enablers & Barriers
- Barrier: Liability between data controllers
- Barrier: Understanding of the data, and it's limitations, between controllers/researchers/DPOs etc
- Barrier: Desire to monetise vs. data quality/feasibility of projects

Addition by attendee:
We need to develop systems where we have trusted research groups within institutions and that governance from one organisation can be directly correlated/equated with the governance from another e.g. a trusted researcher passport -  as a governance person I am aware that we only value processes within our own institution, and that we don't take the assurances from elsewhere with as much credibility as we sometimes could. I think that if we look to develop a trusted researcher passport which works in a cross-institutional way, then we can look to reduce the time to conducting analysis. The benefit of this would be that there would be an additional level of transparency there, where other institutions would have sight of all of the research interests of an individual/research group. It's not 100% thought out, but represents an evolution in how federation between institutions could work.

**Comment by manics** [comment]
Published
