### ISSUE TITLE
DARE call: coordinate WGs

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#131]
### Detail

Coordinate WG leads about submission to DARE UK phase2 community call

### Actions

- [ ] Write email to WG leads asking about their plans

### Who can help

@manics

**Comment by manics** [comment]
Emailed CyberSec and Funding & Sustainability WG chairs.
We're already know or are in contact with the chairs for the other WGs.

**Comment by manics** [comment]
On the UK TRE side SATRE, and the IG group discussed on the UK TRE list, submitted bids. CMWG didn't.
