### ISSUE TITLE
Decide process for Jisc Mailing list

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#14]
### Summary

Decide process for Jisc Mailing list

### Detail

On any contact page we create, we should be clear what Jisc provisions we have, answering questions like:
- What lists exist
- What they can be used for
- How to subscribe

The main issue being a lot of discussion in this discussion list filling people's inboxes, and NHS emails automatically rejecting Jisc mail lists. It might be better to have an announcements mailing list that is more formal, post only, and the discussion mailing list for more in depth discussions.

## Actions
- [ ] Decide what mailing lists we want
- [ ] Set up these mailing lists
- [ ] Publish links and details on the website Contacts page
- [ ] Decide and document the process for reply all etc (see comment below)
- [ ] Decide and document process for how cold outreach to the mailing list works (see comment below)

**Comment by harisood** [comment]
It's annoying when inboxes get clogged with email threads that most people don't have interest in... we should look into updating the JISC settings to not reply all automatically.

This might then be annoying for when you DO want to reply all. Maybe instead we should be directing longer discussions to take place on Slack? Or as @manics has previously suggested an announcement mailing list and a discussion one?

**Comment by harisood** [comment]
When people reach out cold to us wanting to contact the mailing list, what is our process? Suggested process from @hardakerm: 

> pitch goes out to the community via one of the co-chairs so as not to invite anyone and everyone with a commercial-idea to start spamming the list?

I think this works well for now, and if we decide there is a better way (e.g. monthly newsletter) we can update this!

**Comment by manics** [comment]
Most people won't change the reply address, so removing the default reply-all effectively means most discussions become private which I don't think we want. Slack is a fine as an additional option to the mailing list, but we've seen with the UKRSE slack there's little discussion even amongst RSEs in UKTRE, so I don't think it'll work as the only channel. My preference is still to either have a new announcements list which only list moderators can post to, limit email to no more than oen a week/fortnight on average, and keep the existing list as is.

**Comment by manics** [comment]
If we get requests saying this is too much I think we direct those people to the announcements list only, and in our quarterly events we can summarise any significant discussions that have taken place on the list. There's a good chance that if something substantive is discussed it'll lead to a breakout discussion anyway- and as meeting organisers we can be proactive about suggesting that. There's no solution that's going to work for everyone.

**Comment by harisood** [comment]
This conversation is being moved over to #45
