### ISSUE TITLE
December quarterly meeting - catch-all issue

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#15]
### Summary

All tasks for the December Quarterly meeting

### Actions
- [x] Establish which events manager we will use to organise the event
- [x] Create event and publish - https://lu.ma/uktredecember
- [x] Share the event with the community
- [x] Identify projects to run project workshops
- [x] #35 
- [x] Share reminders with the community - see comms plan on Community GD
- [x] Add [agenda](https://www.uktre.org/en/latest/events/wg_workshops/2023-12-05-december-meeting/index.html) to the website
- [x] [Update agenda with new developments](https://github.com/uk-tre/website/issues/24)
- [x] Email all announcement/workshop/discussion people with final details
- [x] Email all attendees final agenda, and reminder for any community announcements
- [x] #41 
- [x] Prepare collaborative note for the day, share in advance
- [x] Revisit wording about project and discussion sessions, make it clearer
- [x] Write report from meeting - In this PR https://github.com/uk-tre/website/pull/35
- [x] Upload recording to YouTube
- [x] Circulate report
- [ ] Review and process feedback from meeting (publish figures and open relevant issues) - this can be included in the report for the day

We can add items to the above as they arise

**Comment by harisood** [comment]
This should include a brief end-of-year celebration at the end

**Comment by harisood** [comment]
Registration has been created here: https://lu.ma/uktredecember

**Comment by harisood** [comment]
Initial comms sent, reminder will go out on Wed 22nd!

**Comment by Davsarper** [comment]
We now need to identify projects to include, few attendees so far have suggested topics. Engage with those who have and are showing interest

**Comment by Davsarper** [comment]
# Updates from 21 Nov meeting

## Agenda and timing

| Time | Agenda Item |
| ---- | ----------- |
| 13:30 - 13:45 | Welcome and intro |
| 13:45 - 14:30 | Keynote plus Q&A  |
| 14:30 - 14:45 | Community updates |
| 14:45 - 14:55 | Break |
| 14:55 - 15:00 | Intro to breakout rooms |
| 15:00 - 15:45 | Breakout rooms (more general/more specific) |
| 15:45 - 15:55 | Break |
| 15:55 - 16:00 | Intro to breakout rooms |
| 16:00 - 16:45 | Breakout rooms (more general/more specific) |
| 16:45 - 17:00 | Wrap up |

## Breakouts rooms

Based on feedback from previous ones we have decided to have fewer, longer sessions and simultaneously run 'project problem solving sessions' and 'general discussions on a topic'.
Before breaking out we will present the topics so people can make an informed decision on which one to join

## To Do

- [ ] Reach to attendees who suggested topics and ask them to provide furhter details
  - [ ] Project sessions: what they expect to get out, who they would benefit to have in the room, materials for attendees
  - [ ] Discussion sessions: prompts and questions 
- [ ] Update agenda
- [ ] revisit wording about project and discussion sessions, make it clearer
- [ ] Prepare collaborative note for the day, share in advance

**Comment by Davsarper** [comment]
On Nov 28 discussed current registrations and and proposed topics, which cna becombined and which require further clarifications.
Direct work is done on the corresponding spreadsheet (not suitable for public sharing).

**Comment by Davsarper** [comment]
Initial sessions will be recorded, breakouts will not (and so rely on good notes)

**Comment by harisood** [comment]
The PR is awaiting review: https://github.com/uk-tre/website/pull/35

**Comment by Davsarper** [comment]
This is now unblocked, review ready. Perfect for anyone to review and commit suggestions

**Comment by Davsarper** [comment]
Does https://github.com/uk-tre/website/pull/35 closes this issue? Task list says to circulate, are we making any announcement on the report being ready? Might be a bit too late in the calendar but can be a note on the email we send about March event

**Comment by manics** [comment]
IIRC @harisood is going to send an email with the proposed 2024 meeting dates to see if there are any major clashes, so the two reports could be included.

**Comment by harisood** [comment]
Lol later today was actually today, will close this issue now
