### ISSUE TITLE
Create a 'deliverables' one pager for the website based on the funding proposal

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#21]
### Summary

Create a 'deliverables' one pager for the website based on the funding proposal

### Detail

This will be a starting point for anyone to see what we're focusing on now for the next 5 months, and how it links into our use of the project board. It should icnlude:

- Summaries of our deliverables
- Names for each one
- How this links into the repo and project board

### Who can help

@Davsarper

**Comment by harisood** [comment]
Once this is done, we should:
- [ ] Create labels that link to each deliverable as referenced in this one pager
- [ ] Create project board views that split out current tasks per deliverable

**Comment by harisood** [comment]
This should include a vision and mission statement in 'our story', maybe also for homepage of website?

**Comment by Davsarper** [comment]
Should include 'mission statement': "It is the starting point for everyone who arrives or is the TRE space. If you are tasked with anything, this will be the reference, the place to go."

**Comment by harisood** [comment]
Funding has now finished

**Comment by harisood** [comment]
This will be covered in issue 16 of the website (updating 'Current Focus')
