### ISSUE TITLE
Create list of pre-existing and proposed working groups

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#24]
### Detail

This list should be easily findable on the website. It should also link to #19 so it's clear what is required for each WG

### Actions

- [ ] Create a list of proposed and current WGs to live on the website

**Comment by harisood** [comment]
One proposed working group: Funding & Sustainability (of the community)

**Comment by Davsarper** [comment]
Do we need a Community or WG label?

**Comment by manics** [comment]
Overlaps with https://github.com/uk-tre/community-management/issues/30

**Comment by harisood** [comment]
An idea of a group: the [NHS heath Research IG Working Group](https://community.jisc.ac.uk/taxonomy/term/ig-working-group)

**Comment by harisood** [comment]
This will come out of the #82
