### ISSUE TITLE
Create board view categorised by deliverable

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#25]
### Detail

This should make it easier to break down tasks. Some thoughts:
- A view for each of the deliverables that we label in #21 
- A view for 'easy wins'
- A timeline view (if appropriate)

Anything else?

- organise main view
- Add categories and priority to all issues
  - Evaluate usefulness and either always include or abandon

### Actions

- [x] Decide what we should create initial views for
- [ ] Create view to categorise by deliverable
- [ ] Link to this from the deliverables/one pager webpage

### Who can help

@Davsarper

**Comment by harisood** [comment]
Also @Davsarper can u make the project board public

**Comment by Davsarper** [comment]
I am assigning categories and priority ot everythign, to start using those fields to orgnaise views. let's see hwo useful it is.
Also priority may not be correctly assigned to every issue, but this will let us ore easily identifiy that and correct

**Comment by Davsarper** [comment]
This is done via the view 'By Deliverable', note that grouping is done with project field 'Category' as they were created attending to the proposal.
Another option would be to use label BUT, labels are currently more granular and that would create more groups. Also labels not only correspond to deliverables but are used for more operational designations.
Yet it should be considered as we move forward wheter or not the view needs a different configuration or grouping

**Comment by Davsarper** [comment]
This is done via the view 'By Deliverable', note that grouping is done with project field 'Category' as they were created attending to the proposal.
Another option would be to use label BUT, labels are currently more granular and that would create more groups. Also labels not only correspond to deliverables but are used for more operational designations.
Yet it should be considered as we move forward wheter or not the view needs a different configuration or grouping

**Comment by harisood** [comment]
@Davsarper looks good! But we should make sure the categories of deliverable read the same as the summary deliverable one pager stuff in [here](https://github.com/uk-tre/website/pull/21/files#diff-a86d23c2a2e586f20215d56f012102c56096c3c2ae8142f4f9fcbe7275e17549)

**Comment by Davsarper** [comment]
Pushed back to backlog to focus on Governance docs/processes. WIll pick up as part of funded phase closing tasks

**Comment by harisood** [comment]
Funding how now completed so not relevant
