### ISSUE TITLE
Establish whether old working groups exist

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#30]
### Detail

From previous iterations of the community, we had 3 functioning working groups:
- CMWG
- Funding & sustainability
- Open Source & Open Standards

And 1 that struggled to get going
- Information Governance

As we re-adapt how we work, we should understand whether these groups are still operating, and want to continue under the new structure

This will probs need to be done once #19  is completed, and will influence what goes in #work 

### Actions

- [ ] Reach out to the organisers of each group and see if they are still running

### Who can help

@dav

**Comment by harisood** [comment]
Their one pagers have been saved on the internal GD under `Working groups` -> `Old working groups` for now, so we have them stored as we restructure

**Comment by manics** [comment]
I think we should change the opensource/standards WG to just open-standards, and leave a potential open-source WG for later

**Comment by harisood** [comment]
This is covered in #24
