### ISSUE TITLE
Proposal for Community communication and working spaces

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#40]
### Detail

Create a proposal on how we want to use each space: chiefly jisc mailing list, any other lists, slack

- Are we pointing people to the slack space now? As a workign or general discussion space
- Are we creating an announcements separate list? Can we achieve the same just with jisc setting?

To be done this week, discuss async and ratify next Tuesday

### Actions

- [ ] Sketch proposal here or slack, Hari and David
- [ ] Communicate to chairs and CMWG members
- [ ] Decide together
- [ ] Put it in writing to present at  event
- [ ] Once approved update the related document
- [ ] Add document to website

### Who can help

@manics @harisood @hardakerm @balintstewart77

**Comment by harisood** [comment]
I think we should make the Slack the communication hub (with e.g. separate channels for different working groups etc.), with the Jisc mailing list being used for announcements and base-level comms channel. I would want to avoid people leaving the community because they're getting too many emails

**Comment by manics** [comment]
I tihnk we should create a new announcements list, and keep the existing list unchanged:
https://github.com/uk-tre/community-management/issues/14#issuecomment-1824636759

**Comment by harisood** [comment]
Let's ask this at the meeting - last time people said it'd be overkill, we can ask again if it now feels appropriate

**Comment by manics** [comment]
How are we going to present this? We know there's a problem, we also know that not everyone is going to speak up, so we need to present the background/reasoning too and not just the proposal.

**Comment by harisood** [comment]
> How are we going to present this?

"Present the background/reasoning too and not just the proposal"

Question and answer in same comment 😅

**Comment by Davsarper** [comment]
>  last time people said it'd be overkill
Actually, this is why we decided to bring it to the event. Some people answered it would be overkill, most did not answer and a few left. Assuming the feedback was not to create the list is listening to only a few voices.
The CMWG majority still thought an announcement list would be best.

**Comment by Davsarper** [comment]
This conversation is splitting in too many ways, it is clear (I think) we want to ask about the announcement lists but also about the overall proposal for spaces (?). So, do we reference this proposal/issue or #14 during the Dec event?
I would say this proposal, which I then should finalise today. The rest of the CMWG should chime in, take it to slack?
