### ISSUE TITLE
Create glossary Working Group

### ISSUE THREAD

**Issue by rmbaxter67** [uk-tre/community-management#46]
### Detail

The cross-project TRE-and-related-concepts glossary developed during the DARE UK driver projects is currently on [Google Docs](https://docs.google.com/document/d/1SJ6CJG8yHzsvtU7MyzdNOF_S0fZVJb_i/edit). It's a great starting point for a generally useful UK-wide one. It could be hosted at GH/DAREUK, or it could be hosted here. I'd like to see it here. Appropriate?

### Actions

- [x] Decide whether hosting & managing TRE vocabulary at uk-tre makes sense.
- [x] Canvas community on how to go about it (cf. [this comment](https://github.com/uk-tre/community-management/issues/46#issuecomment-1842693201))
- [x] Establish WG for this work following the process as described in #18 

### Who can help

@rmbaxter67

**Comment by manics** [comment]
I support creating a new repo in this org (probably another readthedocs site since it's the easiest?) to host the glossary. I think the first question is to agree who has the authority to resolve all the suggestions on the google doc, as this is the work of several projects. Once we agree that I'm happy to help setup the site and convert the gdoc.

**Comment by rmbaxter67** [comment]
Quick answer is probably nobody. We could make a proposal to the mailing list, saying: here's a useful vocab; we'd like to host it on UK-TRE; we propose to take the latest snapshot, accept all changes, convert all major comments into issues and put it here. I'm happy to do this, as sponsor of the original projects (which might give my enough authority to make the proposal at least!). 

I'd suggest we **not** import any project or product-specific info but just keep to general terms.

**Comment by manics** [comment]
Sounds good to me!

**Comment by rmbaxter67** [comment]
Suggestion from the list from Milan M: could we also integrate the vocabulary that was created to describe various activities and entities involved in the data linkage process that we have mapped out when we were looking at the Grampian Safe Haven ? They could potentially be seen as more detailed elements of the workflow (which is already mentioned in the glossary). It would be good to get insights from others to see how well this vocabulary maps onto the activities in other TREs  https://tre-provenance.github.io/SHP-ontology/releases/v0.2/index-en.html

**Comment by harisood** [comment]
This feels like it fits with @crickpetebarnsley & @hardakerm's suggestion for a TRE/SDE terminology working group - not sure if you guys have thoughts!

Do we need a new repo? Slightly concerned about repo overload... could it not be simpler for now to keep it as a Google Doc, for which only the people running the working group have edit access? And everyone else suggest access only. Could still name and tag versions from this and keeps it non-technical for now, we can also point to it from the UK TRE site

**Comment by jim-smith** [comment]
Happy to volunteer some time from SDC-Reboot Community of interest to add in relevant terms from the glossary we created for the GRAIMatter project describing AI models, risk types, and legal issues surrounding them

**Comment by manics** [comment]
Also I discovered Datamind has a nice online glossary
https://datamind.org.uk/glossary/

Are there any other TRE glossaries? How do we manage them?

**Comment by rmbaxter67** [comment]
Our problem here may not be a lack of glossaries but a bounty of glossaries we don't know about! Maybe start a simple resource webpage that collects pointers to ones we learn about. Then we can take a view about what (if anything) is missing and whether to compile YAG or a GoG.

**Comment by harisood** [comment]
> YAG or a GoG

What do these acronyms mean 😅

I agree that it would be good to combine the glossaries we have, and determine where what exists is good enough, where there are conflicts, and whether we need our own one

**Comment by rmbaxter67** [comment]
A thought on reconciling (a number of *) existing glossaries: dictionary entries often have multiple definitions, because, well, language. Why not copy that in a common glossary, and: where definitions differ only slightly, merge them; where definitions differ for good reasons of context, etc, list them as separate definitions, tagged with an abbreviation for the source -- eg, DM (DataMind), SP (SHP Ontology), etc.

* I wouldn't suggest we look beyond a half-dozen or so, most of which have been mentioned above.

**Comment by harisood** [comment]
@rmbaxter67 to have a conversation with @hardakerm about whether this fits into her and Pete's WG

**Comment by hardakerm** [comment]
had conversation with @rmbaxter67 and think it's not likely that this will coincide with the SDE/TRE definitions WG scope, but we will keep lines of communication open

**Comment by rmbaxter67** [comment]
Over on [Google Docs](https://docs.google.com/spreadsheets/d/1qublBBkpYpNgwKm5HPFD1F7WPvaYaBpY/) is my first pass spreadsheet. I've merged the[ DARE UK Drivers glossary](https://docs.google.com/document/d/1SJ6CJG8yHzsvtU7MyzdNOF_S0fZVJb_i/edit) with the [DataMind glossary](https://datamind.org.uk/glossary/) -- with astonishingly little overlap. I've added a "context" column to the DARE glossary to match the "category" column in DataMind. I've a blank sheet waiting to ingest the [SHP Ontology glossary](https://tre-provenance.github.io/SHP-ontology/releases/v0.2/index-en.html) but haven't fingured out a neat way to scrape that yet.

**Comment by KirstieJane** [comment]
This is really important work @rmbaxter67 ! Strong support for a glossary working group - and also some "term of the week" or "metadata conflict of the month" community engagement vectors!

**Comment by Davsarper** [comment]
It was discussed and agreed to turn this into a WG (to be further defined)

**Comment by harisood** [comment]
@rmbaxter67 I've changed the title, added an action to formulate a WG, and will move this back to backlog!

**Comment by rmbaxter67** [comment]
Creation started with request for Jiscmail list, uk-tre-glossary@...
Will populate with named folk from March UK TRE session (me, Balint, Kate O'Sullivan and Will Crocombe) and advertise on uk-tre-community.

**Comment by rmbaxter67** [comment]
Working [group charter](https://docs.google.com/document/d/1Vow33Uw5FjipH2hshU_ZRfQDW-R06hosGiAWT9mp8HU/) now in development; aim to knock on the head on 29 April. Co-chairs engaged. Mailing list set up. Action here is complete.

**Comment by Davsarper** [comment]
Hi @rmbaxter67 can you share a view only link that we can circulate with everyone?

**Comment by rmbaxter67** [comment]
View-only charter link:

https://docs.google.com/document/d/1Vow33Uw5FjipH2hshU_ZRfQDW-R06hosGiAWT9mp8HU/edit?usp=sharing

Cheers,
      Rob



Dr Rob Baxter

National Digital Infrastructure Technical Lead

DARE UK (Data and Analytics Research Environments UK)



Wellcome Trust, 215 Euston Road, London, NW1 2BE

Mobile: +44 (0)7732 689 249

Twitter: @DARE_UK1<https://twitter.com/DARE_UK1> | LinkedIn: DARE UK<https://www.linkedin.com/showcase/dareuk>

www.dareuk.org.uk<http://www.dareuk.org.uk/> | Join the DARE UK mailing list<https://dareuk.org.uk/get-involved/>
[cid:f8c21ecc-6a3b-4da3-bda3-f5c01febb50d]

DARE UK<https://dareuk.org.uk/?_hsenc=p2ANqtz-8sXVfAXa4YEjF8B0KMCqCnEHzMAm5hgHa0XxNGJc6ezF9odGH4Dx-tFU8W1CSlskdP3kg7> is funded by UK Research and Innovation (UKRI)<http://www.ukri.org/?_hsenc=p2ANqtz-8sXVfAXa4YEjF8B0KMCqCnEHzMAm5hgHa0XxNGJc6ezF9odGH4Dx-tFU8W1CSlskdP3kg7>, with Phase 1: Design and Dialogue led by
Health Data Research UK (HDR UK)<https://www.hdruk.ac.uk/?_hsenc=p2ANqtz-8sXVfAXa4YEjF8B0KMCqCnEHzMAm5hgHa0XxNGJc6ezF9odGH4Dx-tFU8W1CSlskdP3kg7> and ADR UK (Administrative Data Research UK)<https://www.adruk.org/?_hsenc=p2ANqtz-8sXVfAXa4YEjF8B0KMCqCnEHzMAm5hgHa0XxNGJc6ezF9odGH4Dx-tFU8W1CSlskdP3kg7>.



“Nullius in verba”, The Royal Society



________________________________

**Comment by Davsarper** [comment]
[heart]         David Sarmiento Perez reacted to your message:
________________________________

**Comment by manics** [comment]
Created! Charter in progress, will be a separate issue
