### ISSUE TITLE
Slack access for @nhs.net

### ISSUE THREAD

**Issue by jonnyry** [uk-tre/community-management#47]
### Detail

I'm trying to join the UKTRE Slack Channel but can't because my email address is @nhs.net:

https://ukrse.slack.com/signup?redir=%2Farchives%2FC045ETUPPD0%3Fname%3DC045ETUPPD0#/domain-signup

Could you add @nhs.net to the allowed domain list?  Or alternatively send me an invite?

(I am working with the North West SDE)

### Actions

See above

**Comment by Davsarper** [comment]
Hi @jonnyry this should work for you (and everyone) to join! https://join.slack.com/t/uktrecommunity/shared_invite/zt-26r7jz25d-J5iV0XoqyLepEiKk4XpJVg

**Comment by jonnyry** [comment]
Ah fantastic thanks - I'm in :-)
