### ISSUE TITLE
Progress report for funder (DARE)

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#51]
### Detail

Interim progress report and interim financial report due by 31st Dec, it needs to reflect progress but given the short time the main focus is identifyig risks that could prevent completing the goals set up in the proposal.

### Actions

- [x] Summarize progress based on the board and issues
- [x] Identify risks towards goals
- [x] Identify mitigation strategies
- [x] Write report
- [x] Alan Turing actions
  - [x] Prepare financial report
  - [ ] Send both reports to funder 

### Who can help

@harisood

**Comment by harisood** [comment]
Waiting for review from co-chairs before being submitted to DARE UK

**Comment by harisood** [comment]
Submitted in 23!
