### ISSUE TITLE
Create open invite link to the Community Management working group meetings

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#52]
### Detail

The weekly CM meetings should be open to everyone in the community to join if they want to. Making this link available to the community would be good!

### Actions

- [x] Decide how we make this link available (want to also protect the Zoom link if possible)
- [x] Implement this
- [x] Add invite in event series within Community calendar

**Comment by harisood** [comment]
I could imagine this being e.g. a Google form where you register to have the invite, we confirm that person is part of the community then send it manually

**Comment by Davsarper** [comment]
Retain host capacity to remove participants in case of issues like zoom bombing due to the link being openly available

**Comment by Davsarper** [comment]
@Davsarper to add in the event for this series an invite to slack and explanation to reach CMWG for the link. This way we avoid linking to a zoom link that may break and is only (currently) managed by Turing (due to our settings not allowing external co-hosts(

**Comment by Davsarper** [comment]
Updated event series in Team Up calendar https://teamup.com/event/show/id/b8ryfgvAAPhS6CR9c4EdTKHxP8avTh
