### ISSUE TITLE
Change name of Community Management Working Group

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#53]
### Detail

As we become more formalised, I wonder if it's worth changing our name from CMWG to something like 'Steering Group' or similar - to show more clearly where decisions lie

### Actions

- [ ] Decide if we want to change the name
- [ ] Decide upon new name
- [ ] Update relevant references across repo, community and website

**Comment by manics** [comment]
"Steering group" and "steering council" are terms I've seen used. I think changing the name away from "WG" since it's more a governing body than a WG, but I don't think it's essential to do it now unless there's an external driver.

**Comment by harisood** [comment]
This Steering Group/CMWG differentiation is now covered in our governance docs
