### ISSUE TITLE
March event - Invite NHSE SDE policy person

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#55]
### Detail

During a breakout session in Dec the next step identified was to invite a NHSE SDE policy person to the March event. They may already be in the community but we can extend a direct invitation/ask them to speak or lead a discussion

### Actions

- [x] Go back to notes and discussion participants and identify what the ask would be
- [x] Extend invitation
- [x] Work on the content of the talk: what will it be?
- [x] Add blurb for talk to the ageda

### Who can help

@harisood

**Comment by Davsarper** [comment]
part of #56

**Comment by harisood** [comment]
It would be good to have the 'Keynote' from the NHS SNSDE network, and possibly one or two breakout discussions too

**Comment by harisood** [comment]
Emailed NHS people to extend invitation, will wait for a response

**Comment by harisood** [comment]
Followed up today

**Comment by harisood** [comment]
Chris Russell has confirmed he will give the session

**Comment by harisood** [comment]
Closing as this is now ready
