### ISSUE TITLE
March event - Catch all issue

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#56]
### Detail

Next Community event will happen in March and needs to be planned

### Actions

- [x] Decide date, urgent - 14th March morning
- [x] Communicate hold the date early on
- [x] Create [registration page](https://lu.ma/n7yybonh)
- [x] Create [event page on website](https://www.uktre.org/en/latest/events/wg_workshops/2024-03-14-march-meeting/index.html)
- [x] Create draft agenda, should follow the same format form last event
- [x] Circulate page and invite Community members to participate via updates, keynote, workshops...
- [x] revisit and complete this to-do list
- [x] Finalise agenda - including how to split sessions
- [x] Create HackMDs
- [x] Create slide deck for session
- [x] Circulate final agenda with attendees
- [x] Send facilitation notes to chairs of sessions
- [x] Prepare for CMWG session
- [x] Create June event
- [x] Create feedback form
- [x] Circulate feedback form
- [x] Thank Chris
- [x] Upload recording to YouTube
- [x] Write up event
- [ ] Publish write up to website
- [ ] Share write up and recordings with everyone

#### Related issues

#55 
#16 

### Who can help

@harisood

**Comment by harisood** [comment]
It could be cool to make sure there are sessions that go beyond health - e.g. ONS/administrative data,SMDH, etc. 

Something to think about - could ask specific members from these and similar groups to prepare sessions

**Comment by Davsarper** [comment]
Content keeps being Health focus, including ideas for keynote speakers. Make an effort to include non-health speakers/breaout session leaders.
And for the future do strive to bring keynote speakers from other sectors

**Comment by KirstieJane** [comment]
I've pinged the Turing Way accessibility working group to ask about the moving background for the event website.

I think my gut feeling is that it probably isn't accessible..... if we have to ask then we probably know the answer.....

Noting here that Rob B doesn't love it (from the zoom chat in the meeting).

Suggest static bubbles instead 🍾

**Comment by harisood** [comment]
Happy for this to be shared more widely for registration, even if content not finalised

**Comment by Davsarper** [comment]
Reshare invite in slack and mail list, reminder

**Comment by Davsarper** [comment]
Breakout rooms may be busier for this event, we are thinking that is fine and test how it works so we do not peacemeal conversations too much. We should make sure though that on top of someone leading the convesation there are people facilitating and taking notes. 
We will see how it works this time and use feedback to decide on next events

**Comment by Davsarper** [comment]
Commercial solutions have approached to have a breakout room, discussion in the CMWG meeting is leaning towards enabling the room but with very clear signage that this is a commercial solution and also encouraging the proponents to NOT make just a sales pitch but talk about their approach to TREs and the reason for their solutions. Maximum 20 minutes should be about presenting a commercial solutions and plenty of time should be given to discussions and (though) questions.
This is a trial and we do want to capture feedback from running this kind of sessions

**Comment by Davsarper** [comment]
A bit of a summary of where there are pending discussions:
- [Steering group](https://docs.google.com/document/d/1t4_dTdJEQHZuuF_l915bo_P-lCv0jRHuHvHCus26a8w/edit#heading=h.e9lbbh3jy6hx): There are some outstanding questions around whether the voting of members should be public or private; whether if a member steps down it should be up to the SG to identify an interim replacement or whether a new member should be nominated by the SG and community and voted in straight-away and if so, whether their term would begin from the point they are elected. Finally, there is still debate about how long members of the SG should sit for and if there is a 3-term limit, how best to manage this- Simon has suggested staggering things so that there is an overlap
- [Consensus, review and objections](https://docs.google.com/document/d/1SxFnmMKcfsYaO4wjHdiBfGOgPATIsTwRKaLbyjoN1pA/edit#heading=h.kssfskkg9mt2): some issues to be resolved around what ‘endorsing’ a CG output means vs simply approving an output 
- [Roles & Membership](https://docs.google.com/document/d/1vyEAiD9ccLTINlat1KNQIem3ywS-0ksu8e3bpO6PvN0/edit#heading=h.6grrwfz65znw): , some list members will be anointed and some won’t (ie, Newcastle-committed and not). Were it ever to matter in a discussion, who would ever know? Are we going to tag committed members via the listserv? A two-speed community? And anyone can join.

**Comment by Davsarper** [comment]
@harisood and myself are still asignees here, but that had more to do with orgniasing/delivering. Now that task are write up, would not mind reassessing who does that and when (does this remain in rogress or goes ot planned/backlog?)

**Comment by balintstewart77** [comment]
@Davsarper would you mind sharing the HackMDs for the breakout rooms so that I can start writing the summary up (in another HackMD?)

**Comment by balintstewart77** [comment]
Blocked while we wait for Alan Pinder to approve SATRE breakout discussion (we could update the website with all the bits if we want though?)

**Comment by balintstewart77** [comment]
Alan Pinder approved

> Blocked while we wait for Alan Pinder to approve SATRE breakout discussion (we could update the website with all the bits if we want though?)

**Comment by Davsarper** [comment]
Ready to publish by @manics
