### ISSUE TITLE
Give required access to co-chairs of community

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#6]
### Summary

Decide and give access as appropriate to co-chairs of the UK TRE Community

### Detail

We need to ensure there isn' a single point of failure for the community but ensuring key accounts and details are shared amongst the co-chairs. 

Access should be distributed among everyone's individual accounts where possible, with key admin details only shared with a select group of people. This include:

- [x] The UK TRE community email 
- [x] The UK TRE Community Google drive
- [ ] The Jisc mailing list admins
- [ ] The UK TRE Community eventbrite

What is the best way to share these details, and who should have access?

### Who can help

@Davsarper

**Comment by harisood** [comment]
Also 
- [ ] UK TRE Community GitHub org

**Comment by manics** [comment]
Can we turn on 2FA before adding more people to the GitHub org?

**Comment by harisood** [comment]
Do we think the only people who should be owners of the org are the co-chairs? currently @jemrobinson and @JimMadge are there too, should they be moved to members?

**Comment by harisood** [comment]
Current access can be seen on this [closed document](https://docs.google.com/document/d/1U4XstFbTwzAaCvaPVtFjZjbHDPOp46Bw0E-PQNbQVy8/edit).



Given we have some people with access to each thing, once we've answered the above question I'll close this issue!
