### ISSUE TITLE
Create events calendar

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#61]
### Detail

Based on discussion in #57 we have decided that it is best to have a calendar of all events happening in the TRE space.

These will not be orgnaised by the UK TRE Community and therefore just signposted. Through some curation we will update this calendar and point to it from the website and newsletter

### Actions

- [x] Capture notes and agreement in #57 
- [x] Decide calendar platform
- [x] Create calendar and configure access
- [ ] Add section/link to website - @manics 
- [x] Add events
  - [x] All planned community meetings in #16 
  - [x] Google show and tell
  - [x] All upcoming SDAP meetings
  - [x] SDC reboot meetings
  - [x] SATRE WG meetings
  - [x] [RDS Systems Development Fund Showcase](https://events.teams.microsoft.com/event/56bf19df-17a2-4c49-8dc5-11bb9643da46@039076c6-a0fc-453a-99c4-a9626e422172)
  - [x] [Safe Pod and HDR UK seminar](https://ed-ac-uk.zoom.us/meeting/register/tZwof-uoqTMsGdz2PmGZ9mfCO-bs5aTQOT-A#/registration)
- [x] Add access rights - https://docs.google.com/document/d/1U4XstFbTwzAaCvaPVtFjZjbHDPOp46Bw0E-PQNbQVy8/edit#heading=h.yaju461l7x1t

**Comment by harisood** [comment]
@Davsarper added a list of events I know about so I can close #16 , though I'm sure there's more!

**Comment by Davsarper** [comment]
[Team Up](https://www.teamup.com/pricing/) has the necessary features and acts under GDPR, with minimal data sharing with third parties. Free plan allows to have a master calendar, up to 8 sub calendars (we plan to have just 2) and up to 8 account users (calendar admins, it cna be shared with any number of people).

Main con is having just 1 year of historical data, meaning older events will no be visible. But those we want to have a record of will be in our website won't they?

**Comment by Davsarper** [comment]
Google calendar can be shared pubicly and administered by a specifi group of people, given that we already use Google suite in the TRE Community I would go this route to avoid creating any further accounts (even if I like Team Up better myself)

https://calendar.google.com/calendar/embed?src=f17914d05afbae3d8264cb9dd322bbb555bf65294b5296f7447e5205185ab55d%40group.calendar.google.com&ctz=Europe%2FLondon

**Comment by manics** [comment]
From your brief preview last week Team Up looked nicer, but I think we'd need 3+ years of funding to consider it, so Google calendar sounds like the best option.

We could use use different Google calendar event colours to distinguish between official and unofficial events? Or have a separate calendar for unofficial events but have them displayed on the official one? Advantage of that is people can subscribe to just the official events, disadvantage is people need to subscribe to both.

**Comment by Davsarper** [comment]
Free Team Up offers what we need but the historical data

**Comment by manics** [comment]
We'll only have a record of the official UK TRE events on the website- but maybe that's OK?

**Comment by Davsarper** [comment]
Personally I think so, would like to know what others think. I will prepare the Team Up today and we can decide which one to take forward tomorrow

**Comment by harisood** [comment]
I think a distinction between resources and events may be useful - e.g. Google Cloud meeting, we don't really need a historical record of the meeting, as much as a link to slides/recordings/outputs etc. 

So then if that's the only reason why we'd use google over teamup I say teamup!

**Comment by Davsarper** [comment]
Public link for Team Up calendar https://teamup.com/ksbqmbhymxdbu454aw

**Comment by Davsarper** [comment]
Events can also be shared individually without sharing the whole calendar, for i.e. March event https://teamup.com/event/show/id/maPeohGGuCn8UjZNvgz3qk55j9WsKM

**Comment by manics** [comment]
Should we add the weekly CMWG meetings to the calendar?

**Comment by Davsarper** [comment]
To tackle the limit in historical data it would be good to create an events report

**Comment by Davsarper** [comment]
All event in the main issue added
