### ISSUE TITLE
Create Calendar for members to subscribe

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#62]
### Detail

Having decided dates for calendars and how to include non community organised events, we need a calendar managed by the CMWG to add official and non official events

### Actions

- [ ] select platform, taking encessary features into account (subscription possible, easy to manage, open...
- [ ] Create calendar
- [ ] Give CMWG members right permissions
- [ ] Make it open
- [ ] Add to website

**Comment by harisood** [comment]
Covered by #61
