### ISSUE TITLE
Governance doc creation/amendment process

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#64]
### Detail

This one is a bit meta, but this document is the process for creating a new community governance doc, or amending a pre-existing one.

This can then be the process which we put all the other governance docs through!

### Actions

- [ ] Create first passable version of this doc: 
  - Link: https://docs.google.com/document/d/1o6Z2k3odl6Gh4lgzkrQtDU3b2bkbOD1wVKx1mLXDwBw/edit

**Comment by harisood** [comment]
Initial diagram

![Image](https://github.com/uk-tre/community-management/assets/67151373/b396a354-5060-4def-9d7c-d3ebda132df1)

**Comment by Davsarper** [comment]
Done https://uk-tre.github.io/hugo-website/about/governance/governance-amendments/
