### ISSUE TITLE
Create Steering Group governance document

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#67]
### Detail

Create the governance document for the Steering Group (as different from the Community Management Working Group, which is covered in #18 

Link: https://docs.google.com/document/d/1t4_dTdJEQHZuuF_l915bo_P-lCv0jRHuHvHCus26a8w/edit?usp=sharing

### Actions

- [ ] Draft first version of this doc

**Comment by Davsarper** [comment]
Done https://uk-tre.github.io/hugo-website/about/governance/steering-group/
There are practicalities and discussions open that we should address by September/next election

Standing discussions:
- [Encouraging members to not run indefinitely for the Steering Group](https://github.com/uk-tre/community-management/issues/90)
- [Allowing chairs to pick additional chairs, if we have less than 3](https://github.com/uk-tre/community-management/issues/91)
- [Process for how to remove a chair](https://github.com/uk-tre/community-management/issues/92)
