### ISSUE TITLE
Create Events Management governance document

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#68]
### Detail

Create a document that explains how:
- UK TRE Community events
  - How we endorse
  - How we decide who gets sessions etc.
- Non-UK TRE Community events
  - How we advertise

Link: https://docs.google.com/document/d/1dpl-MC_GDpaACzChrLcxuD2aQl1w-kS8vOkzUpu70us/edit?usp=sharing

### Actions

- [x] Create a first draft of this document

**Comment by Davsarper** [comment]
Done https://uk-tre.github.io/hugo-website/about/governance/events-management/
