### ISSUE TITLE
Upload September meeting videos to YouTube

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#7]
### Summary

Ensure all recorded sessions from the UK TRE Community September meeting are uploaded and openly available on YouTube

### Detail

This includes:
- [x] Uploading the videos to YouTube
- [ ] Adding sections to videos with each new talk/discussion point
- [ ] Transcribing videos and making transcription openly available

**Comment by harisood** [comment]
@hardakerm going to take this on, @harisood to give access and make sure all relevant videos are shared

**Comment by Davsarper** [comment]
Adding myself to this one as well, @hardakerm lmk when you take on this as for the 1st video (intro and keynote) I did some chapter identification and have files at the ready. Also lmk if you find the videos on the drive.
@harisood  you need to upload your breakout room, you should have more than one file, upload the one with the screen share

**Comment by harisood** [comment]
Uploaded mine too!

**Comment by harisood** [comment]
@hardakerm to check if she has access to the UK TRE YT Channel

**Comment by hardakerm** [comment]
I have access - have set aside a few hours on Friday to crack through it

**Comment by harisood** [comment]
Videos uploaded here: https://www.youtube.com/channel/UCd7AZjyH33aCmIojGHMfqEg - thanks @hardakerm !!
