### ISSUE TITLE
Email list management

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#71]
### Detail

@hardakerm raised in the Slack:

"what do we think about sending out surveys via the distribution list... i.e. casting a wide net for representative polling without running into (further) survey fatigue"

A wider question of 'communication streams management' - poss another governance doc... to discuss!

### Actions

- [ ] Discuss this point at the 20/02 Community Management meeting

**Comment by manics** [comment]
Seems fine to me- it's a general discussion list. We've talked about a announce-only or newsletter list which I think is a better solution for people who just want notifications of what is happening, as opposed to trying to compromise on a single list.

**Comment by manics** [comment]
Newsletter issue: https://github.com/uk-tre/community-management/issues/50
