### ISSUE TITLE
Documentation days - catch-all

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#72]
### Detail

We are planning on running 3 community sessions for writing and reviewing community governance documentation.

Details can be found here: https://hackmd.io/ty_bEhtBTrKjmYsJEEP8Qw

This issue is for tracking all tasks required to deliver these sessions

### Actions

- [x] Finalise dates
- [x] Create Zoom events or similar
- [x] Add events to community calendar
- [x] Circulate details with community
- [x] Plan sessions

**Comment by Davsarper** [comment]
Team Up event pages
 - day 1 link: https://teamup.com/event/show/id/jFH1HcLFHoqHQQLuoE2BHACCGee7sg
 - day 2 https://teamup.com/event/show/id/jNBmiiZuGsJ6Zn5NFHqAy4aCNJqy27 
 - Day 3 https://teamup.com/event/show/id/zYdEpvKkT9RBxXebvgbUaZWestap1E

**Comment by Davsarper** [comment]
I think this is done, or it will be after today's session
