### ISSUE TITLE
Deliver presentation at DARE UK Community Group showcase event 23 April - 10 min+QA

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#74]
### Detail

We should have at least one co-chair give a 10 min presentation on "progress made over the course of the funding period, reflections on what could have worked better, and any plans for future activities".

### Actions

- [ ] Decide who wants to go
- [x] Respond to doodle poll with times we can all make
- [ ] Prepare slides by 22/04
- [ ] Send invite out for run through 22/04 11-12
- [ ] Run through slides 22/04 11-12

**Comment by Davsarper** [comment]
- Present what have been done
- As many chairs as can make it should be there
- There will be some discussion later
- Date is being confirmed either end of March or mid April

**Comment by Davsarper** [comment]
- Hari and David going
- @harisood being voluntold to give the presentation: confirm your availability as a priority
- Simon happy to help with preparng the presentation

**Comment by harisood** [comment]
I'll start preparing a presentation, anyone who wants to get involved please get in touch or comment below!

@manics happy to help

Perhaps we can have a quick run through on Monday of the slides
