### ISSUE TITLE
Add event for DARE Community Grant showcase to calendar

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#76]
### Detail

Details here: https://www.eventbrite.co.uk/e/dare-uk-community-groups-showcase-lunchtime-webinar-tickets-853589187237?aff=oddtdtcreator

### Actions

- [x] Add event to teamup calendar

### Who can help

@Davsarper

**Comment by Davsarper** [comment]
Event added to calendar, event page here https://teamup.com/event/show/id/1D6TkydDa5tji2tNBN5hSbzWQzB6f1
