### ISSUE TITLE
Final report and invoice for DARE funded phase

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#78]
### Detail

Funded phase ends 31st March, this will require final financial and progress reports.

### Actions

- [x] Check dates for reports
- [x] Write progress report
- [x] Update actuals
- [x] Create Statement of Expenditure
- [x] Request invoice
- [x] Send invoice to HDR finance
- [x] Send reports to DARE

#### `CG_final_project_reporting.docx`
- [ ] Progress, successes, issues, and any future plans
  - Did the project achieve what it set out to? What key activities took place, and were they successful or not? Have there been any project outputs (please share any links to these)? Were there any issues or learnings that you think we as the DARE UK Team need to hear or be aware of? Do you have future plans for the community group?

#### `HDR UK Project Expenditure Report - UK TRE Community.xlsx`
- [ ] In tab 'Summary' 
  - Please complete your contract reference, project name, project lead (PI), and total award amount from the contract
  - Total spend will pull through from your detailed report. 
  - At the end of the project, please update row 24 with the total invoiced amount, this should agree with the total reported spend for the project
- [ ] In tab 'Detailed expenditure'
  - Please list all staff funded through this award, noting the FTE, institution, post type (new or existing), and whether or not they are direct programme staff, direct programme support staff or general support staff. 
  - Please list all non- staff expenditure and select whether this is direct, direct support cost or general support
  - Where relevant, please add any further detail against specific lines

**Comment by harisood** [comment]
This is complete I think - @Davsarper just sense checking everything from the Turing financial side is sound then we can close this

**Comment by Davsarper** [comment]
We've invoiced and sent financial report yes! Will close
