### ISSUE TITLE
[Discussion] Capped events?

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#80]
### Detail

A thought shared on the Slack - we could theoretically share the community events with all manner of community groups - one would e.g. be the HDR Uk wider list of approx. 800 people.

The question then becomes how many is too many? If 10% of that list were to sign up that would put us at over 150 registered which becomes a completely different management q.

Do we want to think about capped attendance for community events? Or e.g. a scalable plan?

### Actions
- [ ] Add conclussion to #77 
- [ ] Close this issue

Discuss the above

**Comment by Davsarper** [comment]
CMWG meeting 12 March

By principle we do not want to close BUT:
- limited capacity for managing more than 150, if over this number then recruit from community (be explicit that we will not be able to run a good event if people do not volunteer)
- Close registrations (over 150) a week before, we cannot accomodate in a week's time 
- Keynote scalates very well, it is breakout rooms that are more challenging. For the latter we can: recruit, divide breakout rooms, create new zoom rooms entirely, registrate separately for keynote and breakouts (in a single event page) as many people might only come for that

**Comment by Davsarper** [comment]
#77 should include this discussion and actions, then cose

**Comment by Davsarper** [comment]
discussed and agreed not to cap (with some logistics notes). Added decision to #77
