### ISSUE TITLE
Working groups day event

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#82]
### Detail

In April and following the finalisation of the funded phase we will organise a day for working groups to be officially established and help them get started with participation and work. It will happen in person at Turing and online.

Suggested date due to room availability and schedules is 29 april, with 25 April also as an option.

Furhter plans are here https://hackmd.io/nTAAo7fOT_quE18y0NYjnA

Event page link is available upon request.

There is a discrete amount of funding available to cover travel and even some accomodation so people can join. We will decide based on need and to ensure a diverse participation.

### Actions

- [x] Create event
- [x] add event to calendar
- [x] book rooms at Turing
- [x] Finalise agenda (@harisood @Davsarper)
  - [x] WG Introductions
    - [x] Collate all slides in a single slide deck
  - [x] WG discussion
    - [x] Prep logistics for online/in-person initial split
  - [x] Break
    - [x] Prepare Mentimeter/Google Form (what room you want to join and whether you are online)
  - [x] Working groups charter
    - [ ] Create HackMD template for each working group/breakout
- [x] Manage registration, monitoring
  - [x] Invite members from working groups (@manics, @hardakerm, @JimMadge, @balintstewart77)
  - [x] Invite wider community (@harisood @Davsarper)
  - [x] Requests for funding
  - [x] request to change the date
- [x] Confirm if those registered to attend online can't make it in person
- [x] Confirm whether those in-person are definitely able to make it
- [x] Prepare charters and guides for WGs, and share with WG leads
- [x] Share preparation materials with attendees
  - [x]  Ask for an intro slide on each person
  - [x] Share details on pre-existing WGs
  - [x] Share expectations about the day
  - [x] Check dietary requirements
- [x] Create name badges
- [x] Send names of attendees to reception @ turing
- [x] Send arrival instructions to attendees
- [x] Ensure we have access to nice glasses of water
- [x] Book catering
  - [x] Pastries
  - [x] Lunch
  - [x] Snacks for morning break
  - [x] Snacks for afternoon break
- [x] Prepare presentation materials 
- [x] Create list of recommendations of activities for get started sprint
- [x] Collate useful resources for get started sprint
- [x] Manage stationery
  - [ ] Decide what stationery we need
  - [x] Buy stationery
- [x] Run practice session with rooms/tech
  - [ ] Make sure that all mics in Ada Lovelace connect to the same Zoom room
- [x] Make sure facilitators know what they are doing
  - [x] In person - David (lead), Hari, Kirstie, Arielle
  - [x] Online - Jim (lead), James R, Matt, David
  - [x] Logistics - Ale
- [x] Confirm key information with logistics
  - [x] That we have black table for 09:30 - 10:30 & 12:00 - 14:00
  - [x] That there is no divider to start with
  - [x] Make sure that all mics in Ada Lovelace connect to the same Zoom room, but split for breakouts
  - [x] That we have nice water on the black table

### Who can help

@harisood

**Comment by Davsarper** [comment]
Should we make a conscious effort to bring in members of the public? Possibly SATRE PPIEs and others? It would have to a specific ask, to establish a WG of sorts or join others but overall to engage and tell us how to engage them.

**Comment by Davsarper** [comment]
Is this the chance to more systematically think about the public?

**Comment by Davsarper** [comment]
From the CMWG we should focus on enabling and making/helping WGs engage with the public.

 Pete Barnsley’s “Citizen Agency Working Group https://github.com/FrancisCrickInstitute/UK_TRE/tree/main/Citizen%20Agency%20Working%20Group might be a good start

**Comment by Davsarper** [comment]
Today, confirm date

**Comment by Davsarper** [comment]
This will go out today

**Comment by Davsarper** [comment]
"We have funds available for travel, and accomodation if needed, and we will try to cover a share of your costs if possible. Yet if you cannot travel without being sponsored please let us know and we will prioritise you"
what we want to get at:
- fund those unable to attend without cost covered first.
- Then provide some support for as many as people as possible
  - more to those who have to spend more

**Comment by Davsarper** [comment]
Today we have to send a reminder, we should know about all applications for covering expenses asap. We currently have 7 atendees (including those from CMWG)

**Comment by Davsarper** [comment]
We have received this feedback via email:

Working group plan:
How many people will actually be there other than the core team and working group leads – that totals about 10-15 so leaving 15 more people to be in person.  Everyone else would need to be online and this means the group work will be driven by that comms mechanism and not the in-person whiteboard etc style which is the real advantage.  The involvement of people online is pretty rubbish for them in this format.
 
I think the documentation of the working groups should be left to the people taking on those leadership roles and coord activities.
 
As such I do not think spending money (well done for finding the extra!) on some people attending, unless they are leads, is a good idea.
If leads cannot make the meeting unless someone pays (ie their work cannot be organised to match up trips etc) then that is a good use of cash.
Paying others seems arbitrary.
 
Making this open to all is fine but contribution to such an initial structure event is better done through feedback.  So a plenary / comms / questionnaire for each working group to get that feedback seems an alternative.

**Comment by Davsarper** [comment]
This is my answer and opinion (but should not be the only one)

I think your concerns about online-inperson dynamics are correct, and that part of the day (specially documentation) makes more sense for leads. Yet I believe making this event in person can be a great opportunity to encourage others to forms WGs, get engaged in existing ones, and in general connecting with the community and feeling like they can contribute; and offering to cover for non-leading people helps having them on the room and encouraging them to be more active. 

But you are right and we might have to adapt the morning to accommodate for two different “speeds”. I think providing an overview of WGs and the process will be useful for everyone, then those who already know what they want to do/are doing can go straight to formalising that and others can use the time to brainstorm a first proposal to share with the community and explore creating new WGs.

**Comment by harisood** [comment]
Some proposed working groups:
* An idea of a group: the [NHS heath Research IG Working Group](https://community.jisc.ac.uk/taxonomy/term/ig-working-group)
* Funding and sustainability (for the community)

**Comment by Davsarper** [comment]
Closing as event delivered and we have #102 for follow up
