### ISSUE TITLE
DARE UK community group end of project reporting (due Fri 12 April 2024)

### ISSUE THREAD

**Issue by manics** [uk-tre/community-management#83]
### Detail

Complete end of project reporting:
- DARE UK community group end of project reporting (`CG_final_project_reporting.docx`)
- HDR UK Project Expenditure Report (`HDR UK Project Expenditure Report - UK TRE Community.xlsx`)

## `CG_final_project_reporting.docx`
- [ ] Progress, successes, issues, and any future plans
  - Did the project achieve what it set out to? What key activities took place, and were they successful or not? Have there been any project outputs (please share any links to these)? Were there any issues or learnings that you think we as the DARE UK Team need to hear or be aware of? Do you have future plans for the community group?

## `HDR UK Project Expenditure Report - UK TRE Community.xlsx`
- [ ] In tab 'Summary' 
  - Please complete your contract reference, project name, project lead (PI), and total award amount from the contract
  - Total spend will pull through from your detailed report. 
  - At the end of the project, please update row 24 with the total invoiced amount, this should agree with the total reported spend for the project
- [ ] In tab 'Detailed expenditure'
  - Please list all staff funded through this award, noting the FTE, institution, post type (new or existing), and whether or not they are direct programme staff, direct programme support staff or general support staff. 
  - Please list all non- staff expenditure and select whether this is direct, direct support cost or general support
  - Where relevant, please add any further detail against specific lines

**Comment by Davsarper** [comment]
copy over some details to #78 and close

**Comment by Davsarper** [comment]
closing as duplicate after copying info over
