### ISSUE TITLE
June event: Data processing tools for TRE data providers - breakout

### ISSUE THREAD

**Issue by Davsarper** [uk-tre/community-management#99]
### Detail

There has been conversation on the mailing list about discussing data processing tools for providers (pre ingress into TRE).

This seems like a good breakout room, will ask proponents to lead

### Actions

- [ ] Ask proponents to register for event
- [ ] Ask to elad BO
- [ ] send template for BO
- [ ] Update event agenda

**Comment by manics** [comment]
On tomorrows agenda
